steps:
# Step 1: Create a VM instance with the specified configuration
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - compute
    - instances
    - create
    - bar-app-vm
    - --zone=us-central1-a
    - --machine-type=e2-medium
    - --image-family=ubuntu-2204-lts
    - --image-project=ubuntu-os-cloud
    - --boot-disk-size=100GB
    - --boot-disk-type=pd-balanced
    - --tags=http-server,https-server
    - --metadata=startup-script='#! /bin/bash
        sudo mkdir -p /home/bus_jochem
        sudo chown bus_jochem:bus_jochem /home/bus_jochem
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose
        sudo usermod -aG docker bus_jochem
        sudo systemctl enable docker'

# Step 2: Configure firewall rules (if not already configured)
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - compute
    - firewall-rules
    - create
    - allow-http
    - --direction=INGRESS
    - --priority=1000
    - --network=default
    - --action=ALLOW
    - --rules=tcp:80
    - --source-ranges=0.0.0.0/0
  allowFailure: true

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - compute
    - firewall-rules
    - create
    - allow-https
    - --direction=INGRESS
    - --priority=1000
    - --network=default
    - --action=ALLOW
    - --rules=tcp:443
    - --source-ranges=0.0.0.0/0
  allowFailure: true

# Step 3: Copy files to Google Cloud Storage
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', '.', 'gs://Bar-App-Bucket/my-app']

# Step 4: Ensure the target directory exists on the VM
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - compute
    - ssh
    - bar-app-vm
    - --zone=us-central1-a
    - --command='sleep 30 && sudo mkdir -p /home/bus_jochem/my-app'

# Step 5: Copy files from GCS to the new VM
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - compute
    - ssh
    - bar-app-vm
    - --zone=us-central1-a
    - --command='gsutil cp -r gs://Bar-App-Bucket/my-app /home/bus_jochem/my-app'

# Step 6: Run docker-compose on the new VM
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - compute
    - ssh
    - bar-app-vm
    - --zone=us-central1-a
    - --command='cd /home/bus_jochem/my-app && sudo docker-compose up -d'

# Timeout for the entire build
timeout: '1200s'

# Specify the logs bucket
logsBucket: 'gs://ada-project-logs-bucket'