version: '3.9'
services:  
  api_gatway:
    image: devopsfaith/krakend:2.6.0
    container_name: api_gateway
    volumes:
      - ./krakend:/etc/krakend/
    depends_on:
      - bar_service
      - product_service
    ports:
      - "8080:8081"
  bar_service:
    build:
      context: ./Bar_Sale_Service
    container_name: bar_service
    ports:
      - "5002:5002"
  product_service:
    build:
      context: ./Product_Service
    container_name: product_service
    ports:
      - "5001:5001"