version: '3.9'
services:
  keycloak:
    image: keycloak/keycloak:24.0.2
    container_name: keycloak
    user: root
    volumes:
      - ./keycloak_data/:/opt/keycloak/data/
      - "./keycloak_data/server.crt.pem:/etc/x509/https/tls.crt"   # Map certificate to container
      - "./keycloak_data/server.key.pem:/etc/x509/https/tls.key"   # Map private key to container
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/tls.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key
    command:
      - start-dev
    ports:
      - 8082:8080
      - 8443:8443  
  api_gatway:
    image: devopsfaith/krakend:2.6.0
    container_name: api_gateway
    volumes:
      - ./krakend:/etc/krakend/
    depends_on:
      - bar_service
      - product_service
      - user_service
    ports:
      - "8080:8081"
  bar_service:
    build:
      context: ./Bar_Sale_Service
    container_name: bar_service_ct
    ports:
      - "5000:5000"
  product_service:
    build:
      context: ./Product_Service
    container_name: product_service_ct
    ports:
      - "5001:5000"
  user_service:
    build:
      context: ./User_Service
    container_name: user_service_ct
    ports:
      - "5002:5000"
#settings to allow access to internetkeys
#sudo chown -R $USER:$USER keycloak_data
#sudo chmod -R 755 keycloak_data