openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Bar sale Service
  license:
    name: MIT
servers:
  - url: http://localhost:5000/v1.0
paths:
  /user/:
    post:
      summary: Create a User
      operationId: resources.user.User.create
      tags:
        - User records
      requestBody:
        description: User Information
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserIn"
      responses:
        '200':
          description: Created User Record
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    description: The User ID
        '500':
          description: Record with the same name already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /user/{d_id}:
    get:
      summary: Get a User Record
      operationId: resources.user.User.get
      tags:
        - User record
      parameters:
        - name: d_id
          in: path
          description: User identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User Record
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserOut"
        '404':
          description: User record not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete a User Record
      tags:
        - place records
      operationId: resources.user.User.delete
      parameters:
        - name: d_id
          in: path
          description: User Record identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Record was deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnyMsg"
        '404':
          description: User record not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    UserIn:
      required:
        - id
        - name
        - balance
        - date_of_birth
      properties:
        id:
          format: string
        name:
          format: string
        balance:
          format: string
        date_of_birth:
          format: string
    UserOut:
      required:
        - id
      properties:
        id:
          type: number
        name:
          format: string
        balance:
          format: string
        date_of_birth:
          format: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
    AnyMsg:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string